### ISSUE TITLE
Strange behaviour in Morse

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_navigation#186]
When running topological navigation in Morse, I get some very strange robot behaviour. When navigating between two nodes through another node, all connected by move_base, when the robot enters the influence area of the intermediate node it gets stuck and moves sideways. This suggests a bug in morse not a bug in topological navigation. However, if I do the same movements with move_base direct from RViz I don't get the same problem. Also, it really looks to consistently only start occcuring only when the robot enters the influence area.

I have the following topological map:

```
name: topo_bham_cs_1
map: topo_bham_cs_1
pointset: topo_bham_cs_1
last_updated: ''
nodes: 
  - 
    name: ChargingPoint
    map: morse_bham_cs
    pointset: topo_bham_cs_1
    pose: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
    verts: 
      - 
        x: 0.25
        y: 0.689999997616
      - 
        x: -0.0750000029802
        y: 0.689999997616
      - 
        x: -0.40000000596
        y: 0.287000000477
      - 
        x: -0.40000000596
        y: -0.287000000477
      - 
        x: -0.0750000029802
        y: -0.689999997616
      - 
        x: 0.25
        y: -0.689999997616
    edges: 
      - 
        node: Station
        action: undocking
  - 
    name: WayPoint3
    map: morse_bham_cs
    pointset: topo_bham_cs_1
    pose: 
      position: 
        x: -4.28688909266
        y: -3.70573661311
        z: -1.94956707028e-10
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.695137900324
        w: 0.718876414645
    verts: 
      - 
        x: 0.689999997616
        y: 0.287000000477
      - 
        x: 0.287000000477
        y: 0.689999997616
      - 
        x: -0.287000000477
        y: 0.689999997616
      - 
        x: -0.689999997616
        y: 0.287000000477
      - 
        x: -0.689999997616
        y: -0.287000000477
      - 
        x: -0.287000000477
        y: -0.689999997616
      - 
        x: 0.287000000477
        y: -0.689999997616
      - 
        x: 0.689999997616
        y: -0.287000000477
    edges: 
      - 
        node: Station
        action: move_base
      - 
        node: WayPoint2
        action: move_base
  - 
    name: WayPoint1
    map: morse_bham_cs
    pointset: topo_bham_cs_1
    pose: 
      position: 
        x: -4.0303348398
        y: 3.81550800833
        z: -1.93847056462e-11
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.738826116446
        w: 0.673896111918
    verts: 
      - 
        x: 0.689999997616
        y: 0.287000000477
      - 
        x: 0.287000000477
        y: 0.689999997616
      - 
        x: -0.287000000477
        y: 0.689999997616
      - 
        x: -0.689999997616
        y: 0.287000000477
      - 
        x: -0.689999997616
        y: -0.287000000477
      - 
        x: -0.287000000477
        y: -0.689999997616
      - 
        x: 0.287000000477
        y: -0.689999997616
      - 
        x: 0.689999997616
        y: -0.287000000477
    edges: 
      - 
        node: Station
        action: move_base
  - 
    name: Station
    map: morse_bham_cs
    pointset: topo_bham_cs_1
    pose: 
      position: 
        x: -1.2
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    verts: 
      - 
        x: 0.689999997616
        y: 0.287000000477
      - 
        x: 0.287000000477
        y: 0.689999997616
      - 
        x: -0.287000000477
        y: 0.689999997616
      - 
        x: -0.689999997616
        y: 0.287000000477
      - 
        x: -0.689999997616
        y: -0.287000000477
      - 
        x: -0.287000000477
        y: -0.689999997616
      - 
        x: 0.287000000477
        y: -0.689999997616
      - 
        x: 0.689999997616
        y: -0.287000000477
    edges: 
      - 
        node: ChargingPoint
        action: docking
      - 
        node: WayPoint1
        action: move_base
      - 
        node: WayPoint3
        action: move_base
  - 
    name: WayPoint2
    map: morse_bham_cs
    pointset: topo_bham_cs_1
    pose: 
      position: 
        x: -4.50607967919
        y: -8.22885913721
        z: 5.32454771246e-10
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.720434401339
        w: 0.69352308784
    verts: 
      - 
        x: 0.689999997616
        y: 0.287000000477
      - 
        x: 0.287000000477
        y: 0.689999997616
      - 
        x: -0.287000000477
        y: 0.689999997616
      - 
        x: -0.689999997616
        y: 0.287000000477
      - 
        x: -0.689999997616
        y: -0.287000000477
      - 
        x: -0.287000000477
        y: -0.689999997616
      - 
        x: 0.287000000477
        y: -0.689999997616
      - 
        x: 0.689999997616
        y: -0.287000000477
    edges: 
      - 
        node: WayPoint3
        action: move_base

---
```

I am running the bham_nav_2d from the strands_morse repository, using the bham_cs environment, and the latest version of strands_morse.

Here are two screencasts:
- http://www.cs.bham.ac.uk/~burbrcjc/nav1.ogv
- http://www.cs.bham.ac.uk/~burbrcjc/nav2.ogv

Any ideas?
