### ISSUE TITLE
[Topological Prediction] wrong edge_ids, missing edges, and 0.0 transversability probability

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#215]
I just tested the topological prediction in the following map:

```
bruno@bruno-mbp:~$ rosrun topological_utils list_maps 
--------------------------------------------------
Name:             small_lgjune14
Number of nodes:  11
Edge actions:     ['move_base', 'docking', 'undocking', 'doorPassing']
Last modified:    2015-03-19 16:11:47.279000+00:00
```

When I run the service,I get this:

```
bruno@bruno-mbp:~$ rosservice call /topological_prediction/predict_edges "epoch:
  secs: 1427825826
  nsecs: 0" 
edge_ids: ['small_lgjune14__ChargingPoint_WayPoint1', 'small_lgjune14__WayPoint1_WayPoint2', 'small_lgjune14__WayPoint3_WayPoint6', 'small_lgjune14__WayPoint4_WayPoint3']
probs: [0.0, 0.0, 1.0, 0.015384615398943424]
durations: 
  - 
    secs: 17
    nsecs: 761088404
  - 
    secs: 48
    nsecs: 852463148
  - 
    secs: 22
    nsecs: 717355132
  - 
    secs: 51
    nsecs: 571141663

```

The edge_ids are prepended with the topo map name,  not all edges have predictions (I imagine because they weere never executed, but we should use a distance based duration then), and some edges have 0 probability, which will create problems, as the robot will never try to execute it again @Jailander
