### ISSUE TITLE
mislocalisation when docking with 2 charging stations

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#323]
@Jailander I'm having issues getting the robot to figure out it's on ChargingPoint2. See image below.

![screenshot from 2016-09-30 14 59 25](https://cloud.githubusercontent.com/assets/4320588/18994190/93dcc532-871e-11e6-8339-ccf5b18109f1.png)

I have the following:

```
strands@bob:~$ rostopic echo /closest_node 
data: WayPoint26

---
```

```
^Cstrands@bob:~$ rostopic echo /current_node 
data: none

---
```

ChargingPoint2 is the following:

```
 name: ChargingPoint2
      map: lg_march2016
      pointset: lg_march2016
      pose: 
        position: 
          x: -15.8862199783
          y: 12.7305574417
          z: 0.0
        orientation: 
          x: -4.90507012785e-09
          y: -3.17301407371e-09
          z: -0.0203624013811
          w: 0.999792635441
      yaw_goal_tolerance: 0.0
      xy_goal_tolerance: 0.0
      verts: 
        - 
          x: 0.25
          y: 0.689999997616
        - 
          x: -0.0750000029802
          y: 0.689999997616
        - 
          x: -0.40000000596
          y: 0.287000000477
        - 
          x: -0.40000000596
          y: -0.287000000477
        - 
          x: -0.0750000029802
          y: -0.689999997616
        - 
          x: 0.25
          y: -0.689999997616
      edges: 
        - 
          edge_id: ChargingPoint2_WayPoint26
          node: WayPoint26
          action: undocking
          top_vel: 0.55
          map_2d: lg_march2016
          inflation_radius: 0.0
          recovery_behaviours_config: ''
      localise_by_topic: {"topic": "/battery_state", "field": "charging", "val": true, "localise_anywhere": false}
```

Any idea what's going on?
