### ISSUE TITLE
Robot stuck by reconfigure error

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#335]
We are having constant problems with the DWAPlanner reconfigure service not sure why or what is happening anyone has an idea of why?

I created a gist with the output on the robot which is here: https://gist.github.com/Jailander/d2e6d13784da794fe77900ba3b92a4f2

a short version is this:
```bash
[ERROR] [WallTime: 1479809803.090947] Exception in your execute callback: 'NoneType' object has no attribute 'tell'
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 291, in executeLoop
    self.execute_callback(goal)
  File "/home/strands/aaf_ws/src/strands_hri/strands_human_aware_navigation/scripts/human_aware_navigation.py", line 191, in g
oalCallback
    self.resetSpeed()
  File "/home/strands/aaf_ws/src/strands_hri/strands_human_aware_navigation/scripts/human_aware_navigation.py", line 114, in r
esetSpeed
    self.client.update_configuration(self.fast_param)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 219, in update_configuration
    msg    = self._set_service(config).config
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in send_message
    serialize_message(self.write_buff, seq, msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msg.py", line 139, in serialize_message
    start = b.tell()
AttributeError: 'NoneType' object has no attribute 'tell'
```

**Comment by Jailander** [comment]
the DWAPlanner parameters were these:
```YAML
dictitems:
  acc_lim_theta: 3.14
  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_limit_trans: 0.8
  angular_sim_granularity: 0.1
  forward_point_distance: 0.0
  goal_distance_bias: 24.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 3.14
      acc_lim_x: 0.8
      acc_lim_y: 0.0
      acc_limit_trans: 0.8
      angular_sim_granularity: 0.1
      forward_point_distance: 0.0
      goal_distance_bias: 24.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_rot_vel: 1.0
      max_scaling_factor: 0.2
      max_trans_vel: 0.55
      max_vel_x: 0.55
      max_vel_y: 0.0
      min_rot_vel: 0.4
      min_trans_vel: 0.05
      min_vel_x: 0.0
      min_vel_y: 0.0
      name: Default
      occdist_scale: 0.01
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 32.0
      prune_plan: true
      restore_defaults: false
      rot_stopped_vel: 0.01
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 1.7
      state: true
      stop_time_buffer: 0.2
      trans_stopped_vel: 0.01
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 10
      vy_samples: 1
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    state: []
  max_rot_vel: 1.0
  max_scaling_factor: 0.2
  max_trans_vel: 0.55
  max_vel_x: 0.55
  max_vel_y: 0.0
  min_rot_vel: 0.4
  min_trans_vel: 0.05
  min_vel_x: 0.0
  min_vel_y: 0.0
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  prune_plan: true
  restore_defaults: false
  rot_stopped_vel: 0.01
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.01
  use_dwa: true
  vth_samples: 20
  vx_samples: 10
  vy_samples: 1
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
state: []
```
and the human_aware_navigation/DWAPlannerParameters are:

```YAML 
dictitems:
  acc_lim_theta: 3.14
  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_limit_trans: 0.8
  angular_sim_granularity: 0.1
  forward_point_distance: 0.0
  goal_distance_bias: 24.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 3.14
      acc_lim_x: 0.8
      acc_lim_y: 0.0
      acc_limit_trans: 0.8
      angular_sim_granularity: 0.1
      forward_point_distance: 0.0
      goal_distance_bias: 24.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_rot_vel: 1.0
      max_scaling_factor: 0.2
      max_trans_vel: 0.55
      max_vel_x: 0.55
      max_vel_y: 0.0
      min_rot_vel: 0.4
      min_trans_vel: 0.05
      min_vel_x: 0.0
      min_vel_y: 0.0
      name: Default
      occdist_scale: 0.01
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 32.0
      prune_plan: true
      restore_defaults: false
      rot_stopped_vel: 0.01
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 1.7
      state: true
      stop_time_buffer: 0.2
      trans_stopped_vel: 0.01
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 10
      vy_samples: 1
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    state: []
  max_rot_vel: 1.0
  max_scaling_factor: 0.2
  max_trans_vel: 0.55
  max_vel_x: 0.55
  max_vel_y: 0.0
  min_rot_vel: 0.4
  min_trans_vel: 0.05
  min_vel_x: 0.0
  min_vel_y: 0.0
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  prune_plan: true
  restore_defaults: false
  rot_stopped_vel: 0.01
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.01
  use_dwa: true
  vth_samples: 20
  vx_samples: 10
  vy_samples: 1
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
state: []
```

Calling usual move_base geniuses @cdondrup , @bfalacerda , @nilsbore have you seen this?
